version: "3.1"

services:

  payments.test:
    build:
      context: ../
      dockerfile: ./build/docker/Dockerfile
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: 8080
      DB_USER: admin
      DB_PASSWORD: changeme
      DB_NAME: payments
      DB_HOST: postgres.test
      DB_PORT: 5432
    entrypoint: ["/bin/wait-for", "postgres.test:5432", "--", "/usr/local/payments/server", "run"]
    depends_on:
      - postgres.test

  postgres.test:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: payments
    volumes:
      - ./sql/tables.sql:/docker-entrypoint-initdb.d/tables.sql:ro
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin payments"]
      interval: 10s
      timeout: 5s
      retries: 5

  swagger.test:
    image: swaggerapi/swagger-ui:v3.19.4
    environment:
      API_URL: http://localhost:8080/static/swagger.yaml
    ports:
      - 3000:8080
    depends_on:
      - payments.test
